### PR TITLE
using strict mode (and it even caught something!)

### PR DESCRIPTION
**Pull request by JamesCropcho**
Hey @todvora, @wfreeman  and the rest, can you look at this? How do you feel about enabling JavaScript's strict mode?

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Ah, looks like I more to work do with this PR, anyway...

**Comment by JamesCropcho** [comment]
Alright @todvora and @wfreeman, everything is now in strict mode, and all tests pass.

I did change how we handle user input- what are your thoughts on all this?

**Comment by JamesCropcho** [comment]
Hey all, just touching base.

Thoughts on this? Any red flags?

Thanks,
James

**Comment by JamesCropcho** [comment]
Hey all, I'll interpret the radio silence as, "we see no issues." Merging this pull request.

Everybody, let me know if you find issues.

-James

**Comment by todvora** [comment]
Hi @JamesCropcho,
It looks good, thanks!

**Pull request merged**
