### PR TITLE
Collection as array

### PR DESCRIPTION
**Pull request by Acetolyne**
Back to a stable spot It supports array type for the collection variable and fixes all the coding problems, however I simply disabled some of the test parameters for Maven. They do not throw the same exceptions since we parse thru collection names and show the user an error if the collection name does not exist.

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Thanks for submitting this new pull request, Jon. I see a few issues with it, but before I take more of your time, it'd be great if Tomáš could first comment on the potential removal of those tests.

@todvora, thoughts on the removal of those tests? Do we need additional tests for the new functionality? (I assume the answer to the second question is ,"yes?")


Thanks all,
James

**Comment by Acetolyne** [comment]
Yes i wanted to ask you guys about the test removals since I am not as familiar with them as you guys. The program simply can't throw an exception if an array is called for collection name else it will stop when a bad collection name is given instead it shows the user an error, if it threw an exception the program would exit on a bad name given. I don't think this would be a good feature, I like it parsing the names and simply giving a warning that the collection was skipped but am open to your thoughts as well.

**Comment by todvora** [comment]
Hi all,
Thank you for this refactored PR. Now is clear, what changed and where.

Yes, we do need the tests for this functionality :-) It would be great to have covered every possible usage case. 

Would it be possible to follow the same scenario as in current stable version? Check, if the given collections exist and throw exception if at least one of them does not? When they exist, run analysis itself?

Then we should solve somehow the JSON output, when there are several collections provided. Any ideas?

Thank you,
Tomas

**Comment by Acetolyne** [comment]
Yes I could refactor it to still throw the exception do you really think it is better to exit if they give a bad collection name rather than just warn them it was skipped? If so I can recode it to throw the exception again. I thought it would be better just to warn the user than exit the program.

**Comment by Acetolyne** [comment]
So I have it to where it will throw an exception now if even one of the collection names is not present or they spelled it wrong. But what if they specified a collection name that exists but is empty? Should it throw an exception there too and stop the program?

**Comment by todvora** [comment]
Hi @Acetolyne,
Thank you for your message. I do prefer exception in both cases - empty and nonexistent collection. It is consistent with the database handling (also exception) and fits nicely in any commandline workflow. If there is something wrong, you can see it directly from the return code. Otherwise you have to parse the text output itself and guess, if everything went ok.   

Would it be possible to verify collection names before the analysis itself? 

Have you any ideas about valid JSON output in case of several collections analysed? 

Sorry for the load of my questions, but this is significant change and we should handle it with caution.

Thank you,
Tomas

**Comment by Acetolyne** [comment]
Ok I will add in the throw exception on empty collections. 
I already have it (on my local copy) to make sure all collection names are valid then if all are valid run the analysis. 

As far as the valid JSON output right now I simply have it output the same as before but seperated with the headers to further explain I have an output from some sample collections I will add in a minute I am firing up my variety development VM to post these in a minute.

**Comment by Acetolyne** [comment]
This is a bit long but it shows the output format It is the same but there are headers before each output which I guess makes it non-valid JSON formatting, I will do some more testing with features such as he persistResults option

MongoDB shell version: 3.0.1
connecting to: variety
Variety: A MongoDB Schema Analyzer
Version 1.4.1, released 14 Oct 2014
Using query of { }
Using limit of 11
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of json
Using persistResults of false
Using collection of products
[
	{
		"_id" : {
			"key" : "_id"
		},
		"value" : {
			"types" : [
				"ObjectId",
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "name"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "type"
		},
		"value" : {
			"types" : [
				"Array",
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "price"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 7,
		"percentContaining" : 63.63636363636363
	},
	{
		"_id" : {
			"key" : "warranty_years"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 7,
		"percentContaining" : 63.63636363636363
	},
	{
		"_id" : {
			"key" : "available"
		},
		"value" : {
			"types" : [
				"Boolean"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "for"
		},
		"value" : {
			"types" : [
				"Array",
				"String"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "monthly_price"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "term_years"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "color"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data.n"
		},
		"value" : {
			"types" : [
				"Number",
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms.n"
		},
		"value" : {
			"types" : [
				"Number",
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.n"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "brand"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 2,
		"percentContaining" : 18.181818181818183
	},
	{
		"_id" : {
			"key" : "sales_tax"
		},
		"value" : {
			"types" : [
				"Boolean"
			]
		},
		"totalOccurrences" : 2,
		"percentContaining" : 18.181818181818183
	},
	{
		"_id" : {
			"key" : "additional_tarriffs"
		},
		"value" : {
			"types" : [
				"Array"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.amount"
		},
		"value" : {
			"types" : [
				"Number",
				"Object"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.amount.percent_of_service"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.kind"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "cancel_penalty"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "limits.data.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "limits.sms.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	}
]
Using query of { }
Using limit of 11
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of json
Using persistResults of false
Using collection of moreproducts
[
	{
		"_id" : {
			"key" : "_id"
		},
		"value" : {
			"types" : [
				"ObjectId",
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "name"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "type"
		},
		"value" : {
			"types" : [
				"Array",
				"String"
			]
		},
		"totalOccurrences" : 11,
		"percentContaining" : 100
	},
	{
		"_id" : {
			"key" : "price"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 7,
		"percentContaining" : 63.63636363636363
	},
	{
		"_id" : {
			"key" : "warranty_years"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 7,
		"percentContaining" : 63.63636363636363
	},
	{
		"_id" : {
			"key" : "available"
		},
		"value" : {
			"types" : [
				"Boolean"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "for"
		},
		"value" : {
			"types" : [
				"Array",
				"String"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "monthly_price"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "term_years"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 4,
		"percentContaining" : 36.36363636363637
	},
	{
		"_id" : {
			"key" : "color"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data.n"
		},
		"value" : {
			"types" : [
				"Number",
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.data.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms.n"
		},
		"value" : {
			"types" : [
				"Number",
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.sms.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice"
		},
		"value" : {
			"types" : [
				"Object"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.n"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.over_rate"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "limits.voice.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 3,
		"percentContaining" : 27.272727272727273
	},
	{
		"_id" : {
			"key" : "brand"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 2,
		"percentContaining" : 18.181818181818183
	},
	{
		"_id" : {
			"key" : "sales_tax"
		},
		"value" : {
			"types" : [
				"Boolean"
			]
		},
		"totalOccurrences" : 2,
		"percentContaining" : 18.181818181818183
	},
	{
		"_id" : {
			"key" : "additional_tarriffs"
		},
		"value" : {
			"types" : [
				"Array"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.amount"
		},
		"value" : {
			"types" : [
				"Number",
				"Object"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.amount.percent_of_service"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "additional_tarriffs.XX.kind"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "cancel_penalty"
		},
		"value" : {
			"types" : [
				"Number"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "limits.data.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	},
	{
		"_id" : {
			"key" : "limits.sms.units"
		},
		"value" : {
			"types" : [
				"String"
			]
		},
		"totalOccurrences" : 1,
		"percentContaining" : 9.090909090909092
	}
]

**Comment by Acetolyne** [comment]
I would guess its valid JSON output since the persistResults option still works fine, It imports to the new database and collection names just fine, please share your thoughts.

**Comment by Acetolyne** [comment]
My latest commit takes care of the throw exceptions and adds the tests back in, I did not create a new PR since we are still figuring out the JSON, if you think there is an issue there or not my latest commit is at https://github.com/Acetolyne/variety/commit/e66a3c7e30c08963ea2f659b879a12afb6786ac0
I merged with my master branch so the commit doesn't show on this PR.
Once I get word back about any issues you think we have with the JSON output then I will go ahead a create a new PR

**Comment by JamesCropcho** [comment]
I like @todvora's ideas about raising exceptions. He justifies them well. And he is very right to handle this with caution.

I am concerned that the JSON output is not valid, but more importantly, that the array of collections does not delineate which array element is which collection's analysis results.

**Pull request closed without merging**
