### PR TITLE
PR for #136

### PR DESCRIPTION
**Pull request by gimmi**

### CODE REVIEW

**Comment by todvora** [comment]
Thank you for your MR!
May I ask you for one more minor issue? If you could fix errors produced by [Eslint](https://eslint.org/): https://travis-ci.org/variety/variety/jobs/280857597#L812, it would be excellent.

(To reproduce the results on your computer, you have to have node.js installed, then run `npm install` in the Variety directory and then `npm run lint`. This should execute the same check as on Travis-CI). 

Thank you, 
Tomas

**Comment by gimmi** [comment]
Done.

**Comment by todvora** [comment]
Perfect, thank you!

**Comment by todvora** [comment]
Let's merge it, what do you think @JamesCropcho?

**Comment by JamesCropcho** [comment]
That sounds like a good idea, Tomáš ( @todvora ). I will do so now.

I will also bump the version, unless anyone has issues with it.

Mr Gheradi ( @gimmi ), on behalf of all Variety users around the world, I am grateful for your contribution.

**Pull request merged**
