### PR TITLE
Recursive mode and collections as array

### PR DESCRIPTION
**Pull request by Acetolyne**
have added the ability to use an array in place of the collection name, or you may use a single collection name. I have also implemented a new var called mode which when set with var mode='recursive' shows stats for all collections except the system.indexes collection. Has been tested with json formatting and with bad collection names as well. It now skips bad colection names but gives a warning to the user, This lets it continue when there is a bad collection name in an array format.  Please do test and share opinions 
Adds features highlighted in issue #80 and closes issue #15

### CODE REVIEW

**Comment by Acetolyne** [comment]
seems the Travis CI build failed, it does not like how I encapsuled the code in a for loop. I will be working on fixing this asap. please feel free to try out the features still and give me feedback on the functionality, Ill clean my "messy" code.

**Comment by Acetolyne** [comment]
Wow got all my errors fixed except some Travis CI parameters need to be changed now since I slightly changed the flow of the program to add a loop for parsing arrays for the collection name and to parse recursive mode. I made a couple commits not realizing that it was the test parameters causing the build fail lol. Im tired Ill fix the travis ci test parameters within the next couple days. Have a great day people.

**Comment by JamesCropcho** [comment]
Jon, we're going to review this in depth soon. In the meantime, could you again merge the latest `master` from `variety/variety.git` kindly? I've made JSHint settings stricter and this would facilitate the merge. Thanks!

**Comment by JamesCropcho** [comment]
Hi Jon, I'm curious to know- did you run into any issues merging the new `master`. Let me know if so and we can work out something easier, maybe.   -J

**Comment by Acetolyne** [comment]
No James the merge was easy worked great and everything in my repo works the only thing that fails on the Travis CI build is the Travis CI test parameters since there is now a loop it does not throw exceptions where it used to since if a collection is missing in the specified array it will tell the user and continue to the next collection name that the user specified. Therefore I need to modify some of the Travis CI test parameters.  The program itself works great just not the build tests.

**Comment by JamesCropcho** [comment]
Hello Jon, I see we're getting the following JSHint warnings:

```
james@laptop:~/variety-acetolyne$ jshint --config .jshintrc variety.js  | sort

12 errors
variety.js: line 12, col 3, Missing "use strict" statement.
variety.js: line 17, col 7, Redefinition of 'collection'.
variety.js: line 19, col 3, Read only.
variety.js: line 33, col 29, 'db_name' is not defined.
variety.js: line 33, col 3, Read only.
variety.js: line 58, col 38, Unnecessary grouping operator.
variety.js: line 58, col 39, 'mode' is not defined.
variety.js: line 58, col 5, Unnecessary grouping operator.
variety.js: line 68, col 44, Unnecessary grouping operator.
variety.js: line 68, col 5, Unnecessary grouping operator.
variety.js: line 78, col 3, Read only.
variety.js: line 81, col 15, 'parse' was used before it was defined.
james@laptop:~/variety-acetolyne$ 
```
It would be great if you were able to correct these issues. Let me know.

Thanks,
J

**Comment by Acetolyne** [comment]
I see I missed these errors I'm not used to the build checking so I will be working on these errors and will update when I'm done fixing these build problems.

**Pull request closed without merging**
