### PR TITLE
taking query into account when calculating numDocuments and totalOccuren...

### PR DESCRIPTION
**Pull request by jamesdelonay**
...ces for correct reporting in case where query is used.

### CODE REVIEW

**Comment by jamesdelonay** [comment]
Great tool. I was using it to look at variety of various queries when I noticed the issue.

**Comment by todvora** [comment]
Hi @jamesdelonay,
Thank you for your interest in Variety. Documentation about the query param is little bit ambiguous. Until now I always thought about the query as a possibility to filter analyzed documents, where the rest is calculated in the same way as by ```limit``` param. From limit README:

> the tool calculates totalOccurrences and percentContaining from all the collection's documents, even those outside the "limit".

So Variety now handles the query in the same manner. Filters analyzed and does not influence total numbers. But maybe the current behavior does not make any sense. It probably depends on use cases. 

What do you think @JamesCropcho and @wfreeman? We should clearly define, what is the expected behavior. 

Thank you,
Tomas

**Comment by jamesdelonay** [comment]
Hi Tomas,

I was assuming that the expected behavior would be to reflect the variety
of the query since that is really all that is being looked at. Reporting
the variety compared to the total number of records in collection may give
users a false sense of its composition.

Thanks,
James Delonay

**Comment by JamesCropcho** [comment]
Tomáš and James,

I agree that there is ambiguity, and I believe it can be pretty easily resolved by either changing the name of "query" to something more precise, OR to do the above and also add a second precise parameter for James' proposed functionality, OR to remove the current "query" functionality and replace it with James', but with a more precise parameter name. Hopefully that makes sense.

Another option would be on parameter, with a switch to determine which query type.

Of course, naming and naming changes are to be taken very seriously (though I don't mind breaking anything to improve future UI).

Thoughts, including what they might be named?

Let Me Know, and Thanks Sincerely,
James

**Comment by jamesdelonay** [comment]
Hello James and Tomáš,

I have recently pushed another change to my branch. It now takes the
effects of limit into consideration in cases with and without a query. I
hope that you will consider pulling this into variety.js.

Let my explain why I think that it would be beneficial. First, the output
is not even correct in either the case where queries or limits are used.
Often times the total occurrence count of a field will either be zero or
greater then the number of records that are considered. This is clearly a
flaw. The second, it is inaccurate in its reporting of the field scores.
Just try a limit of one and you will see %100 of all documents in the
database are reported to have the fields that are present in this one
record examined. It would be far safer to report the number field
occurrences with respect to the actual number documents investigated.
Nothing needs to be changed, because in its present state it is not even
valid.

Your variety tool for mongodb has been so useful to me and I hope that you
will allow me to give something back.
Thanks for your consideration,
-James Delonay

**Comment by JamesCropcho** [comment]
Hello James D.,

Thank you sincerely for your hard work on this.

Apologies for the delay in our reply. It's been a busy week and will get back to you as soon as we're able.


-James C.

**Comment by jamesdelonay** [comment]
Hey James,

No problem. If you want me to further clarify what I am trying to
accomplish, let me know. I am often times not the best communicator, so I
understand if you want more explanation.

Thanks,
James D.

**Comment by JamesCropcho** [comment]
@todvora @wfreeman I feel like this is a non-trivial change. Do either of you have any thoughts here?

**Comment by todvora** [comment]
Hi,
I had exactly the same feeling as @jamesdelonay, when I was writing the tests. Both ```limit``` and ```query``` are currently extrapolation. But the plain sum of results in selected range seems more natural and expected. 

When someone wants to analyze really only one part of the collection, there is currently no possibility, because the results are always extrapolated to all documents. And it's easier to compute manually the extrapolation from real results, then the other way round.

I would vote for this change. 

Best regards,
Tomas

**Comment by JamesCropcho** [comment]
Tomáš, if you feel that @jamesdelonay has the right idea, I am happy to put my support behind merging this pull request then, unless we hear something from Wes to the contrary.

Otherwise, to move forward- as we would hope(!) this pull causes three tests not to pass, and therefore our build to fail.

Tomáš, would you prefer to update the tests yourself or should we ask @jamesdelonay, perhaps? I'm open-minded- whichever you think is best.

-James

**Comment by todvora** [comment]
No problem, I can update the tests. Of course if @jamesdelonay wants to do that, its perfectly fine too. 
T.

**Comment by JamesCropcho** [comment]
I fine either way, of course. Whatever is best for both of you.

**Comment by jamesdelonay** [comment]
I vote yes. ;)

**Comment by todvora** [comment]
Hi @jamesdelonay,
Sorry that it took us so much time, but I finally managed to merge you pull request and adapt the test cases. Thank you very much for your contribution!

Now we have to update outdated readme, incorporate behavior changes and replace output examples with the ascii results. Working on it ;)

Have a nice day,
Tomas

**Comment by JamesCropcho** [comment]
I agree with Tomáš- thank you very much for your contribution, James. It is a significant improvement for Variety. I hope that you and many others benefit from it.

**Pull request merged**
