### PR TITLE
#77 -fixes output for printing purposes by adding the collection name to...

### LINKED ISSUE #77: Program should output the name of collection
When printing the output nowhere in the ouput does it show which collection the data is for. When you print the collections you then have to rely on the filename to tell you which collection you are looking at. It would be benificial to add the name of the collection into the output of the program for easier documentation.

### PR DESCRIPTION
**Pull request by Acetolyne**
fixes output for printing purposes by adding the collection name to the output of the program. Closes #77

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Jon and everybody,

It seems like in this tiny regard, our otherwise pretty awesome test suite is a bit brittle. The following tests fail:

```
Tests in error:

verifyRestrictedResultsStdout(com.github.variety.test.ParametersParsingTest): 1
testAsciiOutputFormatParam(com.github.variety.test.ParametersParsingTest): 1
verifyDefaultResultsStdout(com.github.variety.test.ParametersParsingTest): 1
testPersistResultsParam(com.github.variety.test.ParametersParsingTest): 1
testDefaultOutputFormatParam(com.github.variety.test.ParametersParsingTest): 1
```

Jon, do you have any experience using Maven and the other Java testing tools we use? If so, perhaps you could look into a fix. I suspect it's an easy fix.

If not, no worries there- we'll see if we can perhaps fix things amongst the core committers.

**Comment by todvora** [comment]
Hi all,
The tests are expecting logs in format ```using _name_ of _value_```. They are parsing those lines and comparing passed parameters in command line with the debug output.

If you provide the collection name like this:
```
log('Using collection of ' + collection);
```
then it will be correctly parsed and will not interfere with the current test cases. Also another test can be then easily added to verify correct debug output of the collection name. 

Could you please modify your PR and include this change? 

Thank you!
Tomas

**Comment by Acetolyne** [comment]
@todvora Thx for some reason it did not like my colon. The new commit passes the Travis CI build. I hope I did this right im not so used to GitHub but I was not sure if I should have made a new pull request or just had both commits in the same pull request. Nonetheless newest commit should be ready to merge. I hope to contribute to this project more as well.

**Comment by JamesCropcho** [comment]
Thanks, Jon. Yes, the tests pass now, and I have merged into `master`. We appreciate your contributions, as do all Variety users, and any future improvements you would be able to make would be very much appreciated. --James

**Pull request merged**
