### PR TITLE
Refactor collection reference

### PR DESCRIPTION
**Pull request by tggreene**
Preferring the more permissive .getCollection(x)  interface over direct member access as it allows databases [beginning with _](https://docs.mongodb.com/manual/reference/method/db.getCollection/#db.getCollection).

### CODE REVIEW

**Comment by tggreene** [comment]
By databases, I really mean collections!

**Comment by JamesCropcho** [comment]
Thanks, Tim. We appreciate your taking the time to make Variety better.

Tomáš ( @todvora ) what do you think? The link Tim added looks pretty solid.

**Comment by todvora** [comment]
Hi everyone,
All the tests are green, no objections here.

Thank you for you contribution Tim!

Best regards,
Tomas

**Comment by JamesCropcho** [comment]
Great, cool! I have merged your changes, Tim. On behalf of all Variety users, thanks much, man.

**Comment by tggreene** [comment]
no problem!

**Pull request merged**
