### PR TITLE
Random sampling of large collections

### PR DESCRIPTION
**Pull request by oz123**
This is quite usefull if the collection is especially large! , here is the output of a sample usage:

```
$ /srv/mongodb/bin/mongo serverIP/admin -u secret --eval "var db_name = 'client'; var collection = 'rfa_conversion.report'; var sampleSize=0.0004" variety.js -p
MongoDB shell version: 2.6.4
connecting to: 10.8.0.20/admin
Variety: A MongoDB Schema Analyzer
Version 1.4.1, released 14 Oct 2014
Using query of { }
Using sampleSize of 0.0004 ( will inspect 204 out of 511372 records) 
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of ascii
Using persistResults of false
removing leaf arrays in results collection, and getting percentages
+---------------------------------------------------------+
| key                 | types    | occurrences | percents |
| ------------------- | -------- | ----------- | -------- |
| ActionFlag          | Boolean  | 204         | 100      |
| ArticleDeeplink     | String   | 204         | 100      |
| ArticleID           | Number   | 204         | 100      |
| ArticleImageURL     | String   | 204         | 100      |
| ArticleName         | String   | 204         | 100      |
| Baskets             | Number   | 204         | 100      |
| BrandImageURL       | String   | 204         | 100      |
| BrandName           | String   | 204         | 100      |
| Channel             | String   | 204         | 100      |
| EAN                 | String   | 204         | 100      |
| FlyerFlag           | Boolean  | 204         | 100      |
| Items               | Number   | 204         | 100      |
| MidCategoryName     | String   | 204         | 100      |
| OnlinePriceImageURL | String   | 204         | 100      |
| PaidPerformance     | Boolean  | 204         | 100      |
| RuleName            | String   | 204         | 100      |
| SEABrand            | String   | 204         | 100      |
| SalesFlag           | Boolean  | 204         | 100      |
| Sub2Channel         | String   | 204         | 100      |
| SubCategoryName     | Number   | 204         | 100      |
| SubChannel          | String   | 204         | 100      |
| TopCategoryName     | String   | 204         | 100      |
| TopChannel          | String   | 204         | 100      |
| TotalOnlinePrice    | Number   | 204         | 100      |
| TotalPrice          | Number   | 204         | 100      |
| _id                 | ObjectId | 204         | 100      |
| mmaDate             | Date     | 204         | 100      |
| mmaWeekNum          | Number   | 204         | 100      |
| mmaWeekYear         | Number   | 204         | 100      |
+---------------------------------------------------------+
```

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Thanks, Oz! I think this is the start of something rather useful!

As an first comment, I noticed the merge has lines like `(function () { 'use strict';`, however these lines are already present in the current `variety.js`. This makes the pull harder to read through.

Do you think you could fix this, to make the pull request relative to the current `variety.js`?

Thank You,
James

**Comment by oz123** [comment]
@JamesCropcho 
Should it not be with `(function () { 'use strict';` ?

**Comment by JamesCropcho** [comment]
Hi @oz123: yes, it should be there. But if you examine variety.js on the master branch you will see that it already is there: https://github.com/variety/variety/blob/master/variety.js#L12.

But it is also present in your pull request, and this is the issue. I would like to examine the diff with only your changes, i.e. against the latest variety.js.

Does this make sense now? Please be in touch  if not, of course!

James

**Comment by oz123** [comment]
@JamesCropcho I can't generate a patch that applies in one step. Is there a way to do this?

**Comment by JamesCropcho** [comment]
Can you get the latest `variety.js` and replace the `variety.js` you are using? Maybe it can be automatically merged, even?

If this looks to be difficult, let me know and we'll think of something else.

J

**Comment by oz123** [comment]
I did a new layman PR...

**Comment by JamesCropcho** [comment]
Hello all, I'm closing this because the action seems to have moved to https://github.com/variety/variety/pull/71. --James

**Pull request closed without merging**
