### PR TITLE
Added option for logging keys and types as they occur

### PR DESCRIPTION
**Pull request by TimLudwinski**
Logs new keys as they occur.  For faster results when going through large datasets and for debugging large mangled databases where the keys are convoluted and will cause the script to go out of memory.  

Prints logs in the following format: `Found new key type "{{keystring.XX.keystring}}" type "{{Type}}"`

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Hello Tim,

Well, I like the idea. Tomáš, any thoughts?

Tim, in the Readme additions could you correct the spelling of "impatient" and capitalize Variety's name, kindly?


Best,
James

**Comment by JamesCropcho** [comment]
Hello Tomáš, what are your thoughts on this?

**Comment by todvora** [comment]
Hi, 
It seems useful and simple, well integrated into Variety. I agree with this addition. 

Should I resolve the conflicts and merge it into master?

**Comment by JamesCropcho** [comment]
Sounds great, Tomáš. While you're in there, kindly correct the spelling of "impatient" and capitalize Variety's name, if you have a few spare moments.

Happy to hear it's useful, simple, and well-integrated: what more could we ask for‽


—James

**Comment by todvora** [comment]
Merged and typos fixed. I also added a simple test for this feature. We should be aware that logging includes also keys which are later removed from results (ending with .XX). Example can be found [here](https://github.com/variety/variety/blob/7e87bd34b39de0eab1eae10762ece994507498c7/spec/ContinuousLoggingTest.js#L16).

**Comment by todvora** [comment]
Thanks @TimLudwinski for your contribution!

**Comment by todvora** [comment]
The test had to be changed slightly to not require specific order of logged messages. Everything should be OK and green now. Sorry for that!

**Comment by JamesCropcho** [comment]
Yes, thank you, Tim! We appreciate your work on this.

**Comment by TimLudwinski** [comment]
Your welcome.  I'm planning on adding an excludeSubkeys parameter when I
get the chance too.  I really like variety; it's a great tool.

Tim

**Comment by JamesCropcho** [comment]
Aw. Thank you kindly, Tim. The sentiment is appreciated.

**Pull request merged**
